/// \file GameDefines.h
/// \brief Game specific defines.

#pragma once

#include "Defines.h"

/// \brief Sprite type.
///
/// Note: NUM_SPRITES must be last.

enum eSpriteType{
  TILE_SPRITE, PLAYER_SPRITE, GUARD_SPRITE, ARMEDGUARD_SPRITE,
  TRAP_PITFALL_SPRITE, TRAP_ELECTRIC_SPRITE, BOSS_GRENADIER_SPRITE,
  PUNCH_SPRITE, BULLET2_SPRITE, BULLET_GRENADE_SPRITE,
  SMOKE_SPRITE, SPARK_SPRITE, EXPLOSION_SPRITE, EXPLOSION_FAKE_SPRITE,
  GREENLINE_SPRITE, BLUELINE_SPRITE,
  MOVEUI_SPRITE, BOXUI_SPRITE, HPUI_SPRITE, GOLD_SPRITE,
  UI_MSG_DEATH, UI_TUT_CONTROLS, UI_SCREEN_TITLE,
  MSN_ROOM_START, MSN_ROOM_LOBBY, MSN_ROOM_LIBRARY, MSN_ROOM_MUSEUM, MSN_ROOM_HALLWAY1, MSN_ROOM_PATIO, 
  MSN_ROOM_RIVERSIDE, MSN_ROOM_QUARTERS, MSN_ROOM_TUNNELS1, MSN_ROOM_TUNNELS2, MSN_ROOM_VAULT, MSN_ROOM_STORAGE,
  NUMA_SPRITE, NUMB_SPRITE, NUMC_SPRITE, NUMD_SPRITE, NVISION_SPRITE, NVGSCREEN_SPRITE,
  BATTERY_SPRITE, SCOREUI_SPRITE, ALERT_SPRITE, BATTERYP_SPRITE, CAMERA_SPRITE, POINTER_SPRITE,
  NUM_SPRITES //MUST BE LAST
}; //eSpriteType

enum facingDir {
	fBACK = 0,
	fFRONT = 3,
	fLEFT = 6,
	fRIGHT = 9
};

enum eStateType {
	PATROL_STATE, IDLE_STATE,
	CAUTION_STATE, ALERT_STATE,
	HURT_STATE
}; //eStateType for different players

enum eMusicState {
	MUS_AMBIENT,
	MUS_ALERT,
	MUS_BOSS,
	MUS_NONE,
};

enum eGameplayState {
	STATE_SCREEN_MAINMENU,
	STATE_SCREEN_ENDLEVEL,
	STATE_GAME_GREEN,
	STATE_GAME_CAUTION,
	STATE_GAME_ALERT,
	STATE_GAME_BOSS,
};